/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UserIdTodoRouteImport } from './routes/$userId/todo'
import { Route as UserIdFilesRouteImport } from './routes/$userId/files'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UserIdTodoRoute = UserIdTodoRouteImport.update({
  id: '/$userId/todo',
  path: '/$userId/todo',
  getParentRoute: () => rootRouteImport,
} as any)
const UserIdFilesRoute = UserIdFilesRouteImport.update({
  id: '/$userId/files',
  path: '/$userId/files',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$userId/files': typeof UserIdFilesRoute
  '/$userId/todo': typeof UserIdTodoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$userId/files': typeof UserIdFilesRoute
  '/$userId/todo': typeof UserIdTodoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$userId/files': typeof UserIdFilesRoute
  '/$userId/todo': typeof UserIdTodoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/$userId/files' | '/$userId/todo'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/$userId/files' | '/$userId/todo'
  id: '__root__' | '/' | '/$userId/files' | '/$userId/todo'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  UserIdFilesRoute: typeof UserIdFilesRoute
  UserIdTodoRoute: typeof UserIdTodoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$userId/todo': {
      id: '/$userId/todo'
      path: '/$userId/todo'
      fullPath: '/$userId/todo'
      preLoaderRoute: typeof UserIdTodoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$userId/files': {
      id: '/$userId/files'
      path: '/$userId/files'
      fullPath: '/$userId/files'
      preLoaderRoute: typeof UserIdFilesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  UserIdFilesRoute: UserIdFilesRoute,
  UserIdTodoRoute: UserIdTodoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
